
name: shared matrix
on:
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      apps: ${{ steps.apps.outputs.apps }}

    steps:
      - name: Define Apps
        id: apps
        run: |
          echo 'apps=["red", "green", "blue"]' >> "$GITHUB_OUTPUT"

  produce-artifacts:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix:
        app: ${{ fromJSON(needs.define-matrix.outputs.apps) }}

    steps:
      - name: Define App
        env:
          app: ${{ matrix.app }}
        run: |
          echo "$app" > app
      - name: Produce Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app }}
          path: app

  consume-artifacts:
    runs-on: ubuntu-latest
    needs:
    - define-matrix
    - produce-artifacts
    strategy:
      matrix:
        app: ${{ fromJSON(needs.define-matrix.outputs.apps) }}

    steps:
    - name: Retrieve Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.app }}

    - name: Report App
      run: |
        cat app