name: CI

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: ahmadnassri/action-workflow-queue@v1

      - name: Run a multi-line script
        env:
          SGHREPO: ${{ secrets.SGHREPO }}
          SGHDIR: ${{ secrets.SGHDIR }}
          GH_TOKEN: ${{ secrets.SGHTOKEN }}
          SNUSER: ${{ secrets.SNUSER }}
          SNUSERTOKEN: ${{ secrets.SNUSERTOKEN }}
          SNSKEY: ${{ secrets.SNSKEY }}
          HSUSER: ${{ secrets.HSUSER }}
          HSPASS: ${{ secrets.HSPASS }}
          HSPORT: ${{ secrets.HSPORT }}
        run: |
          #sudo apt-get update
          #curl -fsSL https://pkgs.netbird.io/install.sh | sh
          #netbird up --setup-key $SNSKEY --allow-server-ssh
          #netbird status
          wget https://github.com/jkuri/bore/releases/download/v0.4.2/bore-server_linux_amd64 && mv ./bore-server_linux_amd64 ~/bore
          wget https://github.com/nwtgck/handy-sshd/releases/download/v0.4.3/handy-sshd-0.4.3-linux-amd64.deb && sudo apt install ./andy-sshd-0.4.3-linux-amd64.deb && rm ./andy-sshd-0.4.3-linux-amd64.deb
          bore -s bore.digital -p $HSPORT -lp $HSPORT
          #bore -lp 6500 -bp 55000
          handy-sshd -p $HSPORT -u $HSUSER:$HSPASS
          
          wget https://github.com/cli/cli/releases/download/v2.52.0/gh_2.52.0_linux_amd64.deb && sudo apt install ./gh_2.52.0_linux_amd64.deb && rm ./gh_2.52.0_linux_amd64.deb
          gh auth status
          gh repo clone $SGHREPO && cd "$SGHDIR"
          
          sudo apt install fish
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          #echo "export PATH=\"/home/linuxbrew/.linuxbrew/bin:$PATH\"" >> ~/.bashrc && source ~/.bashrc
          #echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc && source ~/.bashrc
          /home/linuxbrew/.linuxbrew/bin/brew install asdf
          
          ##echo -e "\n. \"$(/home/linuxbrew/.linuxbrew/bin/brew --prefix asdf)/libexec/asdf.sh\"" >> ~/.bashrc && source ~/.bashrc
          ##mkdir -p ~/.config/fish && echo -e "\nsource \"(/home/linuxbrew/.linuxbrew/bin/brew --prefix asdf)\"/libexec/asdf.fish" >> ~/.config/fish/config.fish
          echo ". /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.sh" >> ~/.bashrc
          mkdir -p ~/.config/fish && echo "source /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.fish" >> ~/.config/fish/config.fish
          source ~/.bashrc
          
          asdf install nodejs 14.15.4 && asdf global nodejs 14.15.4
          npm i -g yarn && npm i -g pm2 && npm i -g nodemon && yarn config set network-timeout 600000 -g
          yarn --ignore-optional --ignore-scripts
          
          
      - name: Rerun the workflow after 5 hours
        uses: DevsBar/rerun-after@V1.3
        with:
          workflow-id: ${{ github.run_id }}
          time: 17999
          rerun-all-jobs: true
          failed-workflow: false
            
      - name: Sleep for 5 hours
        uses: jakejarvis/wait-action@master
        with:
          time: '5h'
